name: 'CI'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
      fail-fast: false

    steps:
      - name: Chekout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
